### PR TITLE
Rule IDs for rollup messages

### PR DESCRIPTION
**Pull request by sergeychernyshev**

### CODE REVIEW

**Comment by frvge** [comment]
The URLs are still valid.

**Comment by sergeychernyshev** [comment]
Any issues with merging this?

**Comment by frvge** [comment]
@XhmikosR Can you triage this?

**Comment by XhmikosR** [comment]
@sergeychernyshev: can you squash the patches?

**Comment by sergeychernyshev** [comment]
@XhmikosR never did that with code already pushed to GitHub.

Can you give me some pointers at what you're looking to get and how to do that?

**Comment by ideadapt** [comment]
@sergeychernyshev I like this article https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request. Maybe that helps.

**Comment by frvge** [comment]
rebase -i HEAD~3 or rebase -i HEAD~4 (one of those two should be OK)

and then force push.

**Comment by sergeychernyshev** [comment]
@XhmikosR @ideadapt @frvge done - squashed and force-pushed so pull request is updated now.

**Pull request merged**
