### PR TITLE
Read from stdin

### PR DESCRIPTION
**Pull request by pluma**
This probably needs testing, but I couldn't figure out how to add CLI tests and make sure they pass for each environment.

I've implemented readStdin for Node, Rhino and WSH with the latter two being based on various online tutorials -- I have only verified the Node implementation.

As the internals always expect a filename, the filename is passed as `"<stdin>"` when reading from stdin. I've tried to keep the changes minimal, but reading from stdin in Node is always async, so I had to introduce a callback.

### CODE REVIEW

**Comment by pluma** [comment]
For the record: the Rhino code seems to work (I verified the stdin implementation by adding prints), but CSSLint's formatter hangs for me even without this PR (it doesn't work with file name arguments either -- maybe I'm doing it wrong).

**Comment by Arcanemagus** [comment]
Any chance that this could be merged or at least reviewed? I would absolutely love to get rid of [AtomLinter/csslint](https://github.com/AtomLinter/csslint) and switch [AtomLinter/linter-csslint](https://github.com/AtomLinter/linter-csslint) back to this official repository now that it seems to be active again, however without this PR I can't do that yet.

If this PR has issues @steelbrain or I can throw together one with the implementation we went with over in the AtomLinter fork which has been working well for our users at least.

**Comment by pluma** [comment]
Should I attempt to rebase this? I'd be willing to look into it if there is any intention to ever merge this PR.

**Comment by XhmikosR** [comment]
@pluma: yes, please fetach and rebase.

**Comment by pluma** [comment]
@XhmikosR I've rebased to upstream master and fixed the conflicts. `npm test` is passing on my machine and travis. Piping files to dist/cli.js behaves as expected, filename is given as `<stdin>`.

**Comment by XhmikosR** [comment]
@pluma: can you add 1-2 tests for this?

**Comment by pluma** [comment]
@XhmikosR any idea how I can test piping files to it?

**Comment by XhmikosR** [comment]
@pluma: sorry, I don't know about that.

**Comment by sergeychernyshev** [comment]
@pluma can we package a sample CSS file with it and do piping using [child_process](https://nodejs.org/api/child_process.html#child_process_options_stdio) or something alike?

**Comment by pluma** [comment]
@sergeychernyshev sure, if you can make any sense of the tests folder and tell me how I can add a test case like that, I'm all in. I just can't justify putting much time into this PR anymore.

**Pull request closed without merging**
