### PR TITLE
Allow linting empty file

### PR DESCRIPTION
**Pull request by joshuaspence**
I feel that linting an empty file should be possible, and should always return no lint errors.

### CODE REVIEW

**Comment by lazd** [comment]
+1, please merge this or fix it elsewhere in the project. I've had two issues filed against `gulp-csslist` (https://github.com/lazd/gulp-csslint/issues/5 and https://github.com/lazd/gulp-csslint/issues/30) and a PR to patch it https://github.com/lazd/gulp-csslint/pull/32.

As an empty file with No CSS IS valid CSS, `CSSLint` should not care.

**Comment by Xaviju** [comment]
**Use case**: When using preprocessors my compiled CSS files are sometimes empty (variables or mixin files) and then they got merged in a single file. I don't want to always CSSlint the big merged file, instead I use to lint the small ones because its faster and have a special task to lint the whole file.

+1 to merge and avoid weird hacks to avoid this error.

**Comment by XhmikosR** [comment]
@joshuaspence: please fetch, rebase and squash.

**Comment by frvge** [comment]
Ping @joshuaspence .

**Comment by XhmikosR** [comment]
@cscott: what's your thoughts? Is this needed after the changes in parser-lib?

**Pull request closed without merging**
