### PR TITLE
add yarn lock and update npm lock

### PR DESCRIPTION
**Pull request by ShavidzeT**
To have a yarn package manager and yarn.lock file in project is very important.

Also there were old packages which I updated and want to review and merge this pull request.

### CODE REVIEW

**Comment by thecotne** [comment]
you don't need more than one lock file

ether yarn.lock or package-lock.json will not be used 
- `yarn` will use `yarn.lock`
- `npm>=5` will use `package-lock.json`
- `npm<=4` will look for `npm-shrinkwrap.json`

**Comment by ShavidzeT** [comment]
@thecotne what's problem to use both package managers?

**Comment by thecotne** [comment]
you can't use both package managers 

npm doesn't give a fuck about `yarn.lock` and yarn on the other hand does not care about `package-lock.json` 

now you need to deal with updating both lock files when you update any dependency

**Comment by ShavidzeT** [comment]
@thecotne I've got your opinion ✌️ 🌴 🌴

**Comment by ShavidzeT** [comment]
fixed and used only yarn 37963355d5f4aa8c8f6e796d19496746d27401c5

**Pull request closed without merging**
