### PR TITLE
pass .csslintrc file path through the CLI

### PR DESCRIPTION
**Pull request by dmi3y**
re #449

Added ability to pass `.csslintrc` file path as: `csslint --config=<path to .csslintrc> <css to lint>`, and as well bit of YUI unit tests to check this functionality.

Notes:
- This also works with CLI as: `csslint --config=<path to .csslintrc> --ignore=<ignores> <css to lint>`,
  in this case the ignore from rc file would be overrided by cli, which is current behavior.
- Rc file could have any valid file name.
- For unit tests, api stubbing used with vm code execusion for main common.js cli code, also fs was faked as json like file.
- Look up file traversing to search closest `.csslintrc`, which was mentioned into #449, is not part of this PR

### CODE REVIEW

**Comment by madskristensen** [comment]
+1 on updating the npm package with this

**Comment by JeffHing** [comment]
+1 on updating the npm package with this also.

**Comment by LeonardoGentile** [comment]
Could you please release this on npm?

**Comment by Arcanemagus** [comment]
@LeonardoGentile see the latest comments on #514 for the (current) reason this hasn't been released yet.

**Pull request merged**
