### PR TITLE
WSH fix

### PR DESCRIPTION
**Pull request by MaxiBul**
WSH does not support `String.trim()`, `Object.create()` and `Object.getPrototypeOf()`.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Can we have some more info about this? Or even better a test?

**Comment by MaxiBul** [comment]
@XhmikosR I just used your script via cscript.exe (Windows 10).
It doesn't work, because of not support methods:  String.trim() ,  Object.create()  and  Object.getPrototypeOf().
This commit fix the problem. What kind of test do you expect?

**Comment by XhmikosR** [comment]
I don't understand what script you are referring to.

Either way, I ran `csslint-wsh.js foo.css` and worked fine from master branch. So I need clear instructions on how to reproduce this.

**Comment by XhmikosR** [comment]
OK, I managed to reproduce it. It happened when an error message was shown.

**Pull request closed without merging**
