### PR TITLE
remove -moz-transform and -o-transform due to minimal usage

### PR DESCRIPTION
**Pull request by lukasoppermann**
`-moz-transform` has been removed in FF16 (currently FF stable is 37) and `-o-transform` at 11.5 (current stable Opera is 27).

If you use something like autoprefixer for the last 2,3 or even 5 versions, you still get an error. 
I would say that suggesting to use vendor-prefixes for very old browser is an anti-pattern or at least not a best-practise and should not be encouraged by something like csslint. 

Also, including a rule like this basically forces you to either turn off the rule (not good) or include all browser prefixes in autoprefixer (also bad).

**Note:** This is true for some other prefixed elements as well. If you merge this one, I am happy to check which other elements can be removed and add another PR.

### CODE REVIEW

**Comment by HerrBertling** [comment]
:+1:

**Comment by bwinton** [comment]
So, I like the idea behind this, but the file you changed is just to recognize vendor-prefixes and suggest that we use the standard fallback, so I _think_ you want to leave that one alone, and instead change line 77 of `src/rules/compatible-vendor-prefixes.js` (and add a test to the bottom of `tests/rules/compatible-vendor-prefixes.js`)…  Does that sound reasonable?

**Comment by lukasoppermann** [comment]
@bwinton thanks, I changed it the way you suggested.

**Comment by lukasoppermann** [comment]
@nschonni any change of getting this merged?

**Comment by himedlooff** [comment]
:+1:

**Comment by lukasoppermann** [comment]
Hey @frvge will this ever be merged?

**Comment by frvge** [comment]
Even though behavior changes, I think it's OK to move forward. FF16 is from 2012 and Opera 11.5 from 2011. Getting an error to slightly update your CSS after 4 years is IMO acceptable. FYI @XhmikosR .

**Pull request merged**
