### PR TITLE
Adds a CLA to contributing.md

### PR DESCRIPTION
**Pull request by mrennie**
Adds a CLA to contributing.md

Fixes https://github.com/CSSLint/csslint/issues/584

Change-Id: If67601630f715c5db6be87f7a741c5f5b1642fd4

### CODE REVIEW

**Comment by bwinton** [comment]
Huh.  I thought I commented on this already.  I apologize if you get a duplicate message!
What do you think about taking [io.js' CLA](https://github.com/nodejs/io.js/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-10) instead?  It seems a little more lenient than the one you're using, and I know the io.js people have been thinking about this kind of thing a lot.

**Comment by mrennie** [comment]
That CLA would work just fine.

**Comment by CWindatt** [comment]
Can we get the CLA added with either wording (Michael's pull request or io.js).  Either wording would allow Eclipse Orion to use newer versions of csslint and the parser.

**Comment by frvge** [comment]
Is it "CSSLint" or "CSS Lint"? The homepage and most documentation makes me think it's CSS Lint, so with a space.

Do we want to share this with the other CSS Lint projects? If yes, then maybe the "CSS Lint project" needs to be rephrased to something like "the projects maintained by the CSS Lint organisation"

**Comment by XhmikosR** [comment]
I'd go with CSSLint but @stubbornella should know better.

**Comment by stubbornella** [comment]
Let's do a space, "CSS Lint"

**Comment by frvge** [comment]
@mrennie can you please make the small changes that were proposed? Thanks.

**Comment by mrennie** [comment]
I ended up having to create a new pull request (https://github.com/CSSLint/csslint/pull/637), so I'm closing this one.

**Pull request closed without merging**
